### PR TITLE
added a few changes to the gallery and the footer background image

### PR DESCRIPTION
**Pull request by Bluebberies**
I added an  'enlarge on click' functionality to the images in the gallery and changed the footer background image position

### CODE REVIEW

**Comment by Bluebberies** [comment]
I added an 'enlarge on click' functionality to the images in the gallery and changed the footer background image position

**Comment by Bluebberies** [comment]
@devgenix @nworiekingslee  please can you review this

**Review by devgenix — APPROVED** [review]
Sorry I was unavailable for a while. 

Thank you for your contributions.

**Comment by Bluebberies** [comment]
Thanks a lot @devgenix  💜

**Pull request merged**
