### PR TITLE
Close event registration before event date.

### PR DESCRIPTION
**Pull request by nworiekingslee**
# Description

- Close event before event date
- Support external registration via links

Fixes # (issue)

## Two new fields were introduced to the table.
 - registration_link
 - registration_closed

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nworiekingslee** [comment]
@jomefavourite @devgenix any idea why the deployment is failing?

**Comment by jomefavourite** [comment]
> @jomefavourite @devgenix any idea why the deployment is failing?

Maybe check Netlify why it fails

**Comment by devgenix** [comment]
@nworiekingslee @jomefavourite 

This is the build logs;

> 2:26:22 PM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
2:26:22 PM: buildbot version: cebdba79ad7a05d907da43c2d1e258ff94a7afe0
2:26:22 PM: Fetching cached dependencies
2:26:22 PM: Failed to fetch cache, continuing with build
2:26:22 PM: Starting to prepare the repo for build
2:26:22 PM: No cached dependencies found. Cloning fresh repo
2:26:22 PM: git clone --filter=blob:none https://github.com/faradayafrica/Faraday-event
2:26:22 PM: Preparing Git Reference pull/32/head
2:26:24 PM: Starting to install dependencies
2:26:24 PM: Python version set to 3.8
2:26:24 PM: Attempting Ruby version 2.7.2, read from environment
2:26:25 PM: Using Ruby version 2.7.2
2:26:25 PM: Started restoring cached go cache
2:26:25 PM: Finished restoring cached go cache
2:26:25 PM: Installing Go version 1.16.5 (requested 1.16.5)
2:26:29 PM: go version go1.16.5 linux/amd64
2:26:29 PM: Using PHP version 8.0
2:26:30 PM: Downloading and installing node v16.20.2...
2:26:30 PM: Downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz...
2:26:31 PM: Computing checksum with sha256sum
2:26:31 PM: Checksums matched!
2:26:33 PM: Now using node v16.20.2 (npm v8.19.4)
2:26:33 PM: Enabling Node.js Corepack
2:26:33 PM: Started restoring cached build plugins
2:26:33 PM: Finished restoring cached build plugins
2:26:33 PM: Started restoring cached corepack dependencies
2:26:33 PM: Finished restoring cached corepack dependencies
2:26:33 PM: No npm workspaces detected
2:26:33 PM: Started restoring cached node modules
2:26:33 PM: Finished restoring cached node modules
2:26:33 PM: Installing npm packages using npm version 8.19.4
2:26:34 PM: npm ERR! code ERESOLVE
2:26:34 PM: npm ERR! ERESOLVE could not resolve
2:26:34 PM: npm ERR!
2:26:34 PM: npm ERR! While resolving: react-meta-tags@1.0.1
2:26:34 PM: npm ERR! Found: react@17.0.2
2:26:34 PM: npm ERR! node_modules/react
2:26:34 PM: npm ERR!   react@"^17.0.2" from the root project
2:26:34 PM: npm ERR!   peer react@"*" from @testing-library/react@12.1.2
2:26:34 PM: npm ERR!   node_modules/@testing-library/react
2:26:34 PM: npm ERR!     @testing-library/react@"^12.1.2" from the root project
2:26:34 PM: npm ERR!   9 more (react-countdown, react-dom, react-helmet, ...)
2:26:34 PM: npm ERR!
2:26:34 PM: npm ERR! Could not resolve dependency:
2:26:34 PM: npm ERR! peer react@"^16.6.0" from react-meta-tags@1.0.1
2:26:34 PM: npm ERR! node_modules/react-meta-tags
2:26:34 PM: npm ERR!   react-meta-tags@"^1.0.1" from the root project
2:26:34 PM: npm ERR!
2:26:34 PM: npm ERR! Conflicting peer dependency: react@16.14.0
2:26:34 PM: npm ERR! node_modules/react
2:26:34 PM: npm ERR!   peer react@"^16.6.0" from react-meta-tags@1.0.1
2:26:34 PM: npm ERR!   node_modules/react-meta-tags
2:26:34 PM: npm ERR!     react-meta-tags@"^1.0.1" from the root project
2:26:34 PM: npm ERR!
2:26:34 PM: npm ERR! Fix the upstream dependency conflict, or retry
2:26:34 PM: npm ERR! this command with --force, or --legacy-peer-deps
2:26:34 PM: npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
2:26:34 PM: npm ERR!
2:26:34 PM: npm ERR! See /opt/buildhome/.npm/eresolve-report.txt for a full report.
2:26:34 PM: npm ERR! A complete log of this run can be found in:
2:26:34 PM: npm ERR!     /opt/buildhome/.npm/_logs/2024-01-31T13_26_33_912Z-debug-0.log
2:26:34 PM: Error during npm install
2:26:35 PM: Failed during stage "Install dependencies": dependency_installation script returned non-zero exit code: 1
2:26:35 PM: Failing build: Failed to install dependencies
2:26:35 PM: Finished processing build request in 13.106s

**Comment by jomefavourite** [comment]
@nworiekingslee maybe change the install script on netlify to this

npm install -f

**Review by devgenix — APPROVED** [review]

**Comment by devgenix** [comment]
@nworiekingslee This doesn't look good
image

**Comment by devgenix** [comment]
> @devgenix can I be assigned to work on that?

Yes please.

Instead of the current look, instead contain the link in a button that opens in another tab when clicked.

The button color should be the brand green.

**Pull request merged**
